version: '3.3'

services:

  api-gateway:
    build:
      context: ../part-09/api-gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - discovery

  rabbitmq:
    image:  "rabbitmq:3"

  discovery:
    image: "consul:1.8"
    environment:
      - CONSUL_LOCAL_CONFIG={"log_level":"info"}

  redis:
    image: "redis:latest"

  postgres-auth:
    image: "postgres:10"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  postgres-user-collections:
    image: "postgres:10"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  postgres-scores:
    image: "postgres:10"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - redis
      - postgres-auth
      - rabbitmq

  cards_0:
    build:
      context: ../part-08/cards
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery

  cards_1:
    build:
      context: ../part-08/cards
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery

  user-collections:
    build:
      context: ./user-collections
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery
      - postgres-user-collections
      - auth
      - rabbitmq

  scores:
    build:
      context: ./scores
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery
      - postgres-scores
      - rabbitmq






